contractors_email = {"Ashok": "ashok_a84@yahoo.co.in",
					 "Bill": "bill_dailytransport@hotmail.com",
					 "Biniam": "bmengstab16@gmail.com",
					 "Caio": "ca_pieza@hotmail.com",
					 "Douglas": "carvalhodd@hotmail.com",
					 "Harman": "info.sahibtrans@gmail.com",
					 "Kiflom": "kiflomfeday1@gmail.com",
					 "Muhammad": "nabeel.sialvi@gmail.com",
					 "Muktar": "muktarhassen.mh@gmail.com",
					 "Redex Brisbane": "redex.transport@gmail.com",
					 "Shane": "shane@afdls.com",
					 "Shiv": "shiv_sharma302@yahoo.com",
					 "Vikas": "vikaspatel8306@gmail.com",
					 "Yohannes": "hjebunegn@y7mail.com",
}